### ISSUE TITLE
Compile warning with missing-field-initializers

### ISSUE THREAD

**Issue by Xuanwo** [MichaHoffmann/tree-sitter-hcl#18]
**Describe the bug**

I'm trying to integrate `tree-sitter-hcl` with [difftastic](https://github.com/Wilfred/difftastic)

But meeting the following compile warning:

```shell
warning: vendor/tree-sitter-hcl-src/scanner.cc: In member function ‘bool {anonymous}::Scanner::scan(TSLexer*, const bool*)’:
warning: vendor/tree-sitter-hcl-src/scanner.cc:99:39: warning: missing initializer for member ‘{anonymous}::Context::heredoc_identifier’ [-Wmissing-field-initializers]
warning:    99 |       Context ctx = { QUOTED_TEMPLATE };
warning:       |                                       ^
warning: vendor/tree-sitter-hcl-src/scanner.cc:117:48: warning: missing initializer for member ‘{anonymous}::Context::heredoc_identifier’ [-Wmissing-field-initializers]
warning:   117 |         Context ctx = { TEMPLATE_INTERPOLATION };
warning:       |                                                ^
warning: vendor/tree-sitter-hcl-src/scanner.cc:145:44: warning: missing initializer for member ‘{anonymous}::Context::heredoc_identifier’ [-Wmissing-field-initializers]
warning:   145 |         Context ctx = { TEMPLATE_DIRECTIVE };
warning:       |                                            ^
```

**To Reproduce**
1. Build with clang

**Expected behavior**
No warning

**Screenshots**
![image](https://user-images.githubusercontent.com/5351546/164759701-c80ec380-4b26-4ae4-9ca9-fb9f19efa293.png)

---

I'm glad to send a PR if fixing the warning looks good to you :smile:

**Comment by MichaHoffmann** [comment]
Hey @Xuanwo, 

Thanks for pointing this out! Yeah, please go ahead with a PR, that would be cool.

We probably should add -Werror here to make sure to catch that in the CI: https://github.com/MichaHoffmann/tree-sitter-hcl/blob/d559c46ba170808b23a73da0cf49f315d221d095/.github/workflows/build.yaml#L22

**Comment by Xuanwo** [comment]
Thanks for the quick response!

I will fix it ASAP.
