### ISSUE TITLE
Parentheses in a heredoc break highlighting

### ISSUE THREAD

**Issue by bravoecho** [MichaHoffmann/tree-sitter-hcl#27]
**Description**
Starting from a valid Terraform file containing heredocs that have parentheses inside blocks:
* if there are no nested blocks, then it works
* if the parentheses are after a nested block, then it works
* if the parentheses are around or before a nested block, then the rest of the file's highlighting breaks

**To Reproduce**

1. In the example file, `tpl5`, add parentheses around the string `"foo"`, everything works normally.
![original](https://user-images.githubusercontent.com/698828/203748763-9de7d2d1-923b-428a-8478-ea07aa6aa4c8.png)
![original-parentheses-added](https://user-images.githubusercontent.com/698828/203748756-4b2f6f67-696c-4d3c-b410-3b741fa1dba6.png)
  
2. In `tpl6`, add parentheses around or after the nested `if` block, the highlight will break.
![original-with-nested-block](https://user-images.githubusercontent.com/698828/203749054-6c1b8c2f-eb85-4bc3-bbc2-82c772c81f72.png)
![Screenshot 2022-11-24 at 09 43 51](https://user-images.githubusercontent.com/698828/203751755-b04a6b6f-3f51-4edf-9db6-0b606413704a.png)
![parentheses-around-nested-block](https://user-images.githubusercontent.com/698828/203749053-f29b344f-66b0-470a-8956-94a323e86070.png)
![Screenshot 2022-11-24 at 09 43 45](https://user-images.githubusercontent.com/698828/203751759-e1b7843c-1c03-44bb-bd95-08a8843e083d.png)

**Expected behavior**
Parentheses around and after nested blocks in a heredoc are valid and correctly highlighted.

**Additional information**
Also verified with nested `for` loops.

**Comment by MichaHoffmann** [comment]
Hey, thanks for the report! Ill look into it over the weekend

**Comment by MichaHoffmann** [comment]
Great find, template expressions were a bit messed up, there were other bugs too with empty if/else or for directives; i added a few tests and fixed precedences; it should work in the next release!

**Comment by MichaHoffmann** [comment]
I think it closed automatically.

**Comment by MichaHoffmann** [comment]
After updating `nvim-treesitter` it works for me now:
![image](https://user-images.githubusercontent.com/17451647/205397429-75dccb9a-7ca7-4ec9-87b1-d735c5be6b85.png)

Can i close the issue?

**Comment by bravoecho** [comment]
Oh my, thank you so much, that was awesome, it's perfect now! I can't tell you how important it was to me, thanks again!
