### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gjabell** [MichaHoffmann/tree-sitter-hcl#36]
Hi Micha,

would it be possible to tag a new release? I'm packaging this project for Alpine Linux and it would be nice to include the fixes since the v1.0.0 release.

Thanks!

**Comment by MichaHoffmann** [comment]
Hey, yeah; ill prepare something this week; i want to clean up the parser from some experiments and release a new experimental dialect before.

**Comment by MichaHoffmann** [comment]
there we go, v1.1.0
